"""High-level show direction engine."""

from __future__ import annotations

from dataclasses import dataclass

from photonic_synesthesia.core.state import (
    MLStreamState,
    MusicStructure,
    PhotonicState,
)


@dataclass
class DirectorDecision:
    """Intent generated by the director before interpreter constraints."""

    target_scene: str
    energy_level: float
    color_theme: str
    movement_style: str
    strobe_budget_hz: float
    melodic_smoothness: float
    laser_aggression: float
    color_drive: float
    laser_motion_energy: float
    laser_color_energy: float
    phrase_role: str
    allow_scene_transition: bool


class DirectorEngine:
    """
    Party Parrot-inspired director layer.

    The director operates at a musical-phrase level. It can suggest new scenes
    continuously, but only allows scene transitions on phrase boundaries to
    prevent chaotic mid-drop jumps.
    """

    def __init__(self, phrase_bars: int = 4):
        self.phrase_bars = max(1, phrase_bars)
        self._last_target_scene = "idle"

    def decide(self, state: PhotonicState) -> DirectorDecision:
        structure = state["current_structure"]
        rule = state["rule_stream"]
        ml = state["ml_stream"]

        energy = self._compute_energy(state)
        target_scene = self._pick_scene(structure, ml)

        at_phrase_boundary = self._at_phrase_boundary(state)
        allow_transition = (
            at_phrase_boundary or target_scene == state["scene_state"]["current_scene"]
        )

        # Hold target scene steady inside phrase boundaries.
        if not at_phrase_boundary and target_scene != self._last_target_scene:
            target_scene = self._last_target_scene
        else:
            self._last_target_scene = target_scene

        color_theme = "warm" if rule["low_band"] >= rule["high_band"] else "cool"
        if structure == MusicStructure.DROP:
            color_theme = "white-hot"

        if structure in (MusicStructure.BUILDUP, MusicStructure.DROP):
            movement_style = "aggressive"
        elif structure == MusicStructure.BREAKDOWN:
            movement_style = "sparse"
        else:
            movement_style = "steady"

        melodic_smoothness = self._compute_melodic_smoothness(state)
        laser_aggression = self._compute_laser_aggression(state, structure)
        color_drive = self._compute_color_drive(state)
        laser_motion_energy = self._compute_laser_motion_energy(state, structure, laser_aggression)
        laser_color_energy = self._compute_laser_color_energy(state, color_drive)
        phrase_role = self._phrase_role(structure)

        strobe_budget = 0.0
        if structure == MusicStructure.DROP:
            # Keep a conservative ceiling for safety.
            strobe_budget = 5.5 + (energy * 1.6) + (laser_aggression * 2.4)
        elif structure == MusicStructure.BUILDUP:
            strobe_budget = 1.8 + (energy * 1.2) + (laser_aggression * 1.4)

        return DirectorDecision(
            target_scene=target_scene,
            energy_level=energy,
            color_theme=color_theme,
            movement_style=movement_style,
            strobe_budget_hz=min(12.0, max(0.0, strobe_budget)),
            melodic_smoothness=melodic_smoothness,
            laser_aggression=laser_aggression,
            color_drive=color_drive,
            laser_motion_energy=laser_motion_energy,
            laser_color_energy=laser_color_energy,
            phrase_role=phrase_role,
            allow_scene_transition=allow_transition,
        )

    def _pick_scene(self, structure: MusicStructure, ml_stream: MLStreamState) -> str:
        if ml_stream.get("confidence", 0.0) >= 0.7:
            return str(ml_stream.get("predicted_scene", "idle"))

        mapping = {
            MusicStructure.INTRO: "intro_ambient",
            MusicStructure.VERSE: "verse_rhythmic",
            MusicStructure.BUILDUP: "buildup_tension",
            MusicStructure.DROP: "drop_intense",
            MusicStructure.BREAKDOWN: "breakdown_ambient",
            MusicStructure.OUTRO: "outro_fade",
            MusicStructure.UNKNOWN: "idle",
        }
        return mapping.get(structure, "idle")

    def _compute_energy(self, state: PhotonicState) -> float:
        audio_energy = float(state["audio_features"]["rms_energy"])
        transient = float(state["rule_stream"]["transient"])
        beat_confidence = float(state["beat_info"]["confidence"])
        weighted = (audio_energy * 0.65) + (transient * 0.25) + (beat_confidence * 0.10)
        return min(1.0, max(0.0, weighted))

    def _compute_melodic_smoothness(self, state: PhotonicState) -> float:
        features = state["audio_features"]
        smoothness = (
            float(features["harmonic_ratio"]) * 0.45
            + float(features["tonal_stability"]) * 0.3
            + float(features["pitch_salience"]) * 0.15
            + (1.0 - float(features["timbral_harshness"])) * 0.1
        )
        return min(1.0, max(0.0, smoothness))

    def _compute_laser_aggression(self, state: PhotonicState, structure: MusicStructure) -> float:
        features = state["audio_features"]
        aggression = (
            float(features["percussive_ratio"]) * 0.34
            + float(features["timbral_harshness"]) * 0.28
            + float(features["spectral_flux"]) * 0.18
            + float(features["onset_density"]) * 0.08
            + float(state["rule_stream"]["transient"]) * 0.12
            + (0.12 if structure == MusicStructure.DROP else 0.04 if structure == MusicStructure.BUILDUP else 0.0)
        )
        return min(1.0, max(0.0, aggression))

    def _compute_color_drive(self, state: PhotonicState) -> float:
        features = state["audio_features"]
        drive = (
            float(features["harmonic_change"]) * 0.42
            + float(features["harmonic_tension"]) * 0.12
            + float(features["pitch_salience"]) * 0.18
            + float(features["pitch_height"]) * 0.1
            + float(features["spectral_flux"]) * 0.15
            + float(features["spectral_centroid"] / 12000.0) * 0.15
        )
        return min(1.0, max(0.0, drive))

    def _compute_laser_motion_energy(
        self,
        state: PhotonicState,
        structure: MusicStructure,
        laser_aggression: float,
    ) -> float:
        features = state["audio_features"]
        motion = (
            laser_aggression * 0.36
            + float(features["onset_density"]) * 0.18
            + (1.0 - float(features["melodic_stability"])) * 0.12
            + float(features["melodic_contour"]) * 0.08
            + float(state["rule_stream"]["transient"]) * 0.16
            + (0.1 if structure == MusicStructure.BUILDUP else 0.16 if structure == MusicStructure.DROP else 0.0)
        )
        return min(1.0, max(0.0, motion))

    def _compute_laser_color_energy(self, state: PhotonicState, color_drive: float) -> float:
        features = state["audio_features"]
        color_energy = (
            color_drive * 0.42
            + float(features["harmonic_tension"]) * 0.18
            + float(features["harmonic_change"]) * 0.14
            + float(features["pitch_salience"]) * 0.1
            + abs(float(features["melodic_contour"]) - 0.5) * 0.12
            + (1.0 - float(features["tonal_stability"])) * 0.04
        )
        return min(1.0, max(0.0, color_energy))

    @staticmethod
    def _phrase_role(structure: MusicStructure) -> str:
        return {
            MusicStructure.INTRO: "intro",
            MusicStructure.VERSE: "groove",
            MusicStructure.BUILDUP: "build",
            MusicStructure.DROP: "drop",
            MusicStructure.BREAKDOWN: "breakdown",
            MusicStructure.OUTRO: "outro",
            MusicStructure.UNKNOWN: "unknown",
        }[structure]

    def _at_phrase_boundary(self, state: PhotonicState) -> bool:
        beat = state["beat_info"]
        if not beat["downbeat"]:
            return False
        # Treat bar 1 as phrase-safe in the current 4/4 model.
        return beat["bar_position"] == 1
