"""High-level show direction engine."""

from __future__ import annotations

from dataclasses import dataclass

from photonic_synesthesia.core.state import (
    MLStreamState,
    MusicStructure,
    PhotonicState,
)


@dataclass
class DirectorDecision:
    """Intent generated by the director before interpreter constraints."""

    target_scene: str
    energy_level: float
    color_theme: str
    movement_style: str
    strobe_budget_hz: float
    allow_scene_transition: bool


class DirectorEngine:
    """
    Party Parrot-inspired director layer.

    The director operates at a musical-phrase level. It can suggest new scenes
    continuously, but only allows scene transitions on phrase boundaries to
    prevent chaotic mid-drop jumps.
    """

    def __init__(self, phrase_bars: int = 4):
        self.phrase_bars = max(1, phrase_bars)
        self._last_target_scene = "idle"

    def decide(self, state: PhotonicState) -> DirectorDecision:
        structure = state["current_structure"]
        rule = state["rule_stream"]
        ml = state["ml_stream"]

        energy = self._compute_energy(state)
        target_scene = self._pick_scene(structure, ml)

        at_phrase_boundary = self._at_phrase_boundary(state)
        allow_transition = (
            at_phrase_boundary or target_scene == state["scene_state"]["current_scene"]
        )

        # Hold target scene steady inside phrase boundaries.
        if not at_phrase_boundary and target_scene != self._last_target_scene:
            target_scene = self._last_target_scene
        else:
            self._last_target_scene = target_scene

        color_theme = "warm" if rule["low_band"] >= rule["high_band"] else "cool"
        if structure == MusicStructure.DROP:
            color_theme = "white-hot"

        if structure in (MusicStructure.BUILDUP, MusicStructure.DROP):
            movement_style = "aggressive"
        elif structure == MusicStructure.BREAKDOWN:
            movement_style = "sparse"
        else:
            movement_style = "steady"

        strobe_budget = 0.0
        if structure == MusicStructure.DROP:
            # Keep a conservative ceiling for safety.
            strobe_budget = 8.0 + (energy * 2.0)
        elif structure == MusicStructure.BUILDUP:
            strobe_budget = 3.0 + (energy * 2.0)

        return DirectorDecision(
            target_scene=target_scene,
            energy_level=energy,
            color_theme=color_theme,
            movement_style=movement_style,
            strobe_budget_hz=min(12.0, max(0.0, strobe_budget)),
            allow_scene_transition=allow_transition,
        )

    def _pick_scene(self, structure: MusicStructure, ml_stream: MLStreamState) -> str:
        if ml_stream.get("confidence", 0.0) >= 0.7:
            return str(ml_stream.get("predicted_scene", "idle"))

        mapping = {
            MusicStructure.INTRO: "intro_ambient",
            MusicStructure.VERSE: "verse_rhythmic",
            MusicStructure.BUILDUP: "buildup_tension",
            MusicStructure.DROP: "drop_intense",
            MusicStructure.BREAKDOWN: "breakdown_ambient",
            MusicStructure.OUTRO: "outro_fade",
            MusicStructure.UNKNOWN: "idle",
        }
        return mapping.get(structure, "idle")

    def _compute_energy(self, state: PhotonicState) -> float:
        audio_energy = float(state["audio_features"]["rms_energy"])
        transient = float(state["rule_stream"]["transient"])
        beat_confidence = float(state["beat_info"]["confidence"])
        weighted = (audio_energy * 0.65) + (transient * 0.25) + (beat_confidence * 0.10)
        return min(1.0, max(0.0, weighted))

    def _at_phrase_boundary(self, state: PhotonicState) -> bool:
        beat = state["beat_info"]
        if not beat["downbeat"]:
            return False
        # Treat bar 1 as phrase-safe in the current 4/4 model.
        return beat["bar_position"] == 1
