"""Platform-level contracts and lightweight control-plane services."""

from photonic_synesthesia.platform.authority import ControlAuthorityService
from photonic_synesthesia.platform.clock import PlatformClock, SystemClock
from photonic_synesthesia.platform.commands import CommandReceipt, InMemoryCommandBus
from photonic_synesthesia.platform.contracts import (
    CommandType,
    ControlLease,
    DirectorSummary,
    ExecutionSnapshot,
    LeaseAcquireRequest,
    LeaseAcquireResponse,
    LiveHealth,
    OperatorCommand,
    OperatorRole,
    PlatformEvent,
    PlatformEventType,
    SafetySummary,
    SemanticFrame,
)
from photonic_synesthesia.platform.events import InMemoryEventBus
from photonic_synesthesia.platform.live_deck_ingest import (
    LiveDeckIngestService,
    ManualTestIngestAdapter,
)
from photonic_synesthesia.platform.live_deck_models import (
    BindingStatus,
    LiveDeckFact,
    LiveDeckSnapshot,
)
from photonic_synesthesia.platform.rig_storage import (
    Conflict,
    RIG_SCHEMA_VERSION,
    RigBridgeError,
    delete_rig,
    detect_address_conflicts,
    get_active_rig_name,
    list_available_profiles,
    list_rigs,
    load_rig,
    materialize_to_fixture_configs,
    rig_path,
    rigs_root,
    save_rig,
    set_active_rig,
)
from photonic_synesthesia.platform.runtime_context import (
    PlaybackContext,
    clear_shared_control_plane_service,
    clear_shared_playback_context,
    get_shared_control_plane_service,
    get_shared_playback_context,
    set_shared_control_plane_service,
    set_shared_playback_context,
)
from photonic_synesthesia.platform.state_service import ControlPlaneStateService

__all__ = [
    "CommandReceipt",
    "CommandType",
    "Conflict",
    "ControlAuthorityService",
    "ControlPlaneStateService",
    "ControlLease",
    "BindingStatus",
    "DirectorSummary",
    "ExecutionSnapshot",
    "InMemoryCommandBus",
    "InMemoryEventBus",
    "LeaseAcquireRequest",
    "LeaseAcquireResponse",
    "LiveHealth",
    "LiveDeckIngestService",
    "LiveDeckFact",
    "LiveDeckSnapshot",
    "OperatorCommand",
    "OperatorRole",
    "PlatformClock",
    "PlatformEvent",
    "PlatformEventType",
    "PlaybackContext",
    "ManualTestIngestAdapter",
    "RIG_SCHEMA_VERSION",
    "RigBridgeError",
    "SafetySummary",
    "SemanticFrame",
    "SystemClock",
    "clear_shared_control_plane_service",
    "clear_shared_playback_context",
    "delete_rig",
    "detect_address_conflicts",
    "get_active_rig_name",
    "get_shared_control_plane_service",
    "get_shared_playback_context",
    "list_available_profiles",
    "list_rigs",
    "load_rig",
    "materialize_to_fixture_configs",
    "rig_path",
    "rigs_root",
    "save_rig",
    "set_active_rig",
    "set_shared_control_plane_service",
    "set_shared_playback_context",
]
